### PR TITLE
Py37

### PR DESCRIPTION
**Pull request by ocefpaf**

### CODE REVIEW

**Comment by ocefpaf** [comment]
I guess we need to wait for a new release with https://github.com/pytroll/pyresample/pull/135, based on the size of the diffs there patching does not seems like a good idea.

**Comment by djhoese** [comment]
@ocefpaf I'll release that now. Thanks for pointing it out.

**Comment by ocefpaf** [comment]
Thanks! There is no hurry though. I'm just trying to get some of my CIs working with Python 3.7 to test the packages I support.

**Comment by djhoese** [comment]
Haha nonsense. I kind of forgot to release this new version anyway. It includes an important bug fix with possible bad things for users so I'd like to get it out there for people to break as soon as possible. Also includes a workaround for cartopy not working with matplotlib 3.0.

**Comment by djhoese** [comment]
Release of 1.10.2 has been made and is on PyPI. I'll wait for the conda-forge bot to pick it up and merge it when it passes.

**Pull request closed without merging**
