### PR TITLE
Add mraspaud and pnuu to maintainers

### PR DESCRIPTION
**Pull request by djhoese**
@mraspaud and @pnuu Is this ok with you?

@ocefpaf is there a way we can do this without creating a new build of the package?

Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by pnuu** [comment]
I'm ok with this.

**Comment by mraspaud** [comment]
Works for me

**Comment by ocefpaf** [comment]
> @ocefpaf is there a way we can do this without creating a new build of the package?

B/c you did not bump the build number this PR won't create a new version of the package. You can also skip the CIs with a commit message like: `[skip ci][skip appveyor][ci skip]`, all 3 together is kind of an overkill but none of those work 100% across the many CI services we are using :grimacing:

BTW, you can merge this without waiting for the CIs.

**Comment by djhoese** [comment]
Yeah I used github's web editor to add them. Didn't have a lot of control over editing multiple files.

**Pull request merged**
